services:
  website:
    container_name: website
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ${PWD}/website/app:/app/website
    networks:
      static-network:
        ipv4_address: ${IPV4_WEBSITE}
  mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - "3306"
    volumes:
      - ./database/script/database-init.sh:/docker-entrypoint-initdb.d/database-init.sh
      - ./database/files/my.cnf:/root/.my.cnf
    # entrypoint: ["./database-init.sh"]
    networks:
      static-network:
        ipv4_address: ${IPV4_DATABASE}

networks:
  static-network:
    ipam:
      config:
        - subnet: 192.168.10.0/24